import Head from 'next/head';
import ImpButton from '../components/ImpButton';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div className={styles.root}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<ImpButton />
		</div>
	);
}
